// data.js
export const exploreData = [
  {
    id: 1,
    title: "Hotel Cairo",
    location: "Cairo",
    images: [
      "https://media.cntravellerme.com/photos/64e4c8101df16d508d79ebac/16:9/w_2580%2Cc_limit/139%2520Pavilion%2520042%2520-.jpg",
      "https://static.wixstatic.com/media/5eff48_0f504a3802c64520ae55fddd238b5ca6~mv2.jpg/v1/fill/w_1480,h_832,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/5eff48_0f504a3802c64520ae55fddd238b5ca6~mv2.jpg",
      "https://media-cdn.tripadvisor.com/media/photo-c/768x250/03/9b/2f/5b/cairo.jpg",
    ],
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 2,

    title: "Hotel Sharm El Sheikh",
    location: "Sharm El Sheikh",
    images: [
      "https://vjm.hu/wp-content/uploads/2022/07/R4G0695_zps0a2ffe1c.jpg",
    ],
    price: 120,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 3,

    title: "Hotel Cairo",
    location: "Cairo",
    image:
      "https://media-cdn.tripadvisor.com/media/photo-c/768x250/03/9b/2f/5b/cairo.jpg",
    price: 100,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 4,

    title: "Hotel Sharm El Sheikh",
    location: "Sharm El Sheikh",
    image: "https://vjm.hu/wp-content/uploads/2022/07/R4G0695_zps0a2ffe1c.jpg",
    price: 120,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 5,

    title: "Hotel Cairo",
    location: "Cairo",
    image:
      "https://media-cdn.tripadvisor.com/media/photo-c/768x250/03/9b/2f/5b/cairo.jpg",
    price: 100,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 6,

    title: "Hotel Sharm El Sheikh",
    location: "Sharm El Sheikh",
    image: "https://vjm.hu/wp-content/uploads/2022/07/R4G0695_zps0a2ffe1c.jpg",
    price: 120,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 7,

    title: "Hotel Cairo",
    location: "Cairo",
    image:
      "https://media-cdn.tripadvisor.com/media/photo-c/768x250/03/9b/2f/5b/cairo.jpg",
    price: 100,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 9,

    title: "Hotel Sharm El Sheikh",
    location: "Sharm El Sheikh",
    image: "https://vjm.hu/wp-content/uploads/2022/07/R4G0695_zps0a2ffe1c.jpg",
    price: 120,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  // Add more hotels as needed
];

export const featuredData = [
  {
    id: 10,
    title: "Hotel Alexandria",
    location: "Alexandria",
    image: "https://medcities.org/wp-content/uploads/2021/06/Alexandria.jpg",
    price: 90,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 11,
    title: "Hotel El Gouna",
    location: "El Gouna",
    image:
      "https://static.wixstatic.com/media/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg/v1/fill/w_1480,h_842,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg",
    price: 150,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 12,

    title: "Hotel Alexandria",
    location: "Alexandria",
    image: "https://medcities.org/wp-content/uploads/2021/06/Alexandria.jpg",
    price: 90,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 13,
    title: "Hotel El Gouna",
    location: "El Gouna",
    image:
      "https://static.wixstatic.com/media/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg/v1/fill/w_1480,h_842,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg",
    price: 150,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 14,

    title: "Hotel Alexandria",
    location: "Alexandria",
    image: "https://medcities.org/wp-content/uploads/2021/06/Alexandria.jpg",
    price: 90,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 15,

    title: "Hotel El Gouna",
    location: "El Gouna",
    image:
      "https://static.wixstatic.com/media/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg/v1/fill/w_1480,h_842,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg",
    price: 150,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 16,

    title: "Hotel Alexandria",
    location: "Alexandria",
    image: "https://medcities.org/wp-content/uploads/2021/06/Alexandria.jpg",
    price: 90,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  {
    id: 17,

    title: "Hotel El Gouna",
    location: "El Gouna",
    image:
      "https://static.wixstatic.com/media/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg/v1/fill/w_1480,h_842,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/5eff48_173cb1b0846446d89e2e41474e6b3e4f~mv2.jpg",
    price: 150,
    price: 100,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    amenities: ["Wifi", "Kitchen", "Heating", "Washer"],
    description: "This is a description of the hotel.",
    reviews: [
      { name: "John", date: "2022-01-01", comments: "Great place!" },
      { name: "Jane", date: "2022-01-02", comments: "Very clean." },
    ],
    host: {
      name: "Host Name",
      image: "host.jpg",
      responseRate: "100%",
      bio: "This is a bio.",
    },
  },
  // Add more featured hotels as needed
];
